import 'dotenv/config';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const CATEGORIES = [
  { slug: 'men-watches', name: "Men's Watches" },
  { slug: 'women-watches', name: "Women's Watches" },
  { slug: 'children-watches', name: "Children's Watches" },
  { slug: 'watches', name: 'Watches' },
];

interface ProductSeed {
  name: string;
  referenceNumber: string | null;
  price: number;
  category_type: string;
  movement: string;
  caseMaterial: string;
  strapMaterial: string;
  waterResistance: string;
  diameterMm: number;
  caseThicknessMm: number;
  functions: string[];
  stockQuantity: number;
  description: string;
}

const products: ProductSeed[] = [
  {
    name: 'Cavadini Chronograph Men CV-1606',
    referenceNumber: 'CV-1606',
    price: 98,
    category_type: 'men-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Leather',
    waterResistance: '10 Bar',
    diameterMm: 46,
    caseThicknessMm: 13,
    functions: ['Chronograph', 'Date', 'Inner World Time Ring', '24-Hour Hand'],
    stockQuantity: 5,
    description: 'Cavadini Chronograph Men Stainless Steel, rotating inner ring brown gold CV-1606',
  },
  {
    name: 'Cavadini Automatic Titanium CV-1604T',
    referenceNumber: 'CV-1604T',
    price: 199,
    category_type: 'men-watches',
    movement: 'Mechanical (Automatic)',
    caseMaterial: 'Titanium',
    strapMaterial: 'Titanium',
    waterResistance: '10 Bar',
    diameterMm: 44,
    caseThicknessMm: 10,
    functions: ['Day-Date Display'],
    stockQuantity: 3,
    description: "Cavadini Men's Watch Automatic Japan Solid Titanium Pilot Classic CV-1604T",
  },
  {
    name: 'Cavadini Globetrotter Blue CV-1000',
    referenceNumber: 'CV-1000',
    price: 69,
    category_type: 'men-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Stainless Steel',
    waterResistance: '10 Bar',
    diameterMm: 47,
    caseThicknessMm: 12,
    functions: ['Day-Date Display'],
    stockQuantity: 3,
    description: 'Cavadini Designer Pilot Watch Men Stainless Steel Blue Silver Calendar CV-1000',
  },
  {
    name: 'Cavadini Leonardo Indo-Arabic CV-330JN',
    referenceNumber: 'CV-330JN',
    price: 89,
    category_type: 'men-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Stainless Steel',
    waterResistance: '10 Bar',
    diameterMm: 40.5,
    caseThicknessMm: 12,
    functions: ['Date', 'Magnifier'],
    stockQuantity: 5,
    description: "Cavadini Men's Watch Date Stainless Steel Indo-Arabic Numerals Black CV-330JN",
  },
  {
    name: 'Cavadini Yukon Nostalgia Rose Gold CV-12K150',
    referenceNumber: 'CV-12K150',
    price: 79,
    category_type: 'men-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Stainless Steel',
    waterResistance: '3 Bar',
    diameterMm: 38,
    caseThicknessMm: 6.5,
    functions: ['2-Hand'],
    stockQuantity: 2,
    description: 'Cavadini Slim Unisex Watch 38mm Stainless Steel Rose Gold Plated Black Dial CV-12K150',
  },
  {
    name: 'Cavadini Diella Rose Gold 45mm',
    referenceNumber: null,
    price: 175,
    category_type: 'women-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Stainless Steel',
    waterResistance: '3 Bar',
    diameterMm: 45,
    caseThicknessMm: 10,
    functions: ['2-Hand'],
    stockQuantity: 1,
    description: 'Cavadini Diella ExtraVaganza Swiss Made Designer Ladies Watch 45mm Stainless Steel Rose Gold',
  },
  {
    name: 'Cavadini Yukon 2 Day-Date CV-4305',
    referenceNumber: 'CV-4305',
    price: 69,
    category_type: 'men-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Leather',
    waterResistance: '3 Bar',
    diameterMm: 42,
    caseThicknessMm: 9,
    functions: ['Day-Date Display'],
    stockQuantity: 5,
    description: "Cavadini Men's Watch Day-Date Stainless Steel Gold-plated Guilloché Classic CV-4305",
  },
  {
    name: 'Cavadini Station Clock Milanese CV-4302',
    referenceNumber: 'CV-4302',
    price: 69,
    category_type: 'men-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Stainless Steel',
    waterResistance: '3 Bar',
    diameterMm: 41.5,
    caseThicknessMm: 9.5,
    functions: [],
    stockQuantity: 5,
    description: "Cavadini Station Clock Men's Watch Stainless Steel Milanese Bracelet 41.5mm CV-4302",
  },
  {
    name: 'Cavadini Caruso Ceramic Bezel CV-745',
    referenceNumber: 'CV-745',
    price: 65,
    category_type: 'women-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Leather',
    waterResistance: '3 Bar',
    diameterMm: 34,
    caseThicknessMm: 9,
    functions: ['Date'],
    stockQuantity: 2,
    description: 'Cavadini Ladies Watch with Ceramic Bezel Steel/White CV-745',
  },
  {
    name: 'Cavadini Skeleton Handwind CV-4837-7040',
    referenceNumber: 'CV-4837-7040',
    price: 299,
    category_type: 'men-watches',
    movement: 'Mechanical (Hand-wind)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Leather',
    waterResistance: '5 Bar',
    diameterMm: 39,
    caseThicknessMm: 10,
    functions: ['2-Hand'],
    stockQuantity: 10,
    description: 'Cavadini Skeleton Watch Swiss Made ETA-Peseux 7040 Hand-wind CV-4837-7040',
  },
  {
    name: 'Cavadini Aquila UNITAS CV-1301',
    referenceNumber: 'CV-1301-6497',
    price: 299,
    category_type: 'men-watches',
    movement: 'Mechanical (Hand-wind)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Leather',
    waterResistance: '5 Bar',
    diameterMm: 46,
    caseThicknessMm: 12,
    functions: ['2-Hand', 'Off-center Small Seconds'],
    stockQuantity: 5,
    description: 'Cavadini Hand-wind Men\'s Watch UNITAS Swiss Made ETA-6497 CV-1301',
  },
  {
    name: 'Zentra Classic Small Second Z-28372-2',
    referenceNumber: 'Z-28372-2',
    price: 59,
    category_type: 'women-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Leather',
    waterResistance: '5 Bar',
    diameterMm: 29,
    caseThicknessMm: 9,
    functions: ['Off-center Small Seconds'],
    stockQuantity: 1,
    description: 'Zentra Ladies Watch Stainless Steel Classic Small Second Brown Leather 29mm',
  },
  {
    name: 'Elysee Düsseldorf Zirconia 23019',
    referenceNumber: '23019',
    price: 49,
    category_type: 'women-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Leather',
    waterResistance: '3 Bar',
    diameterMm: 35,
    caseThicknessMm: 7,
    functions: ['2-Hand'],
    stockQuantity: 1,
    description: 'Elysee Düsseldorf Ladies Watch Stainless Steel Zirconia Designer 23019',
  },
  {
    name: 'Esprit Classic Green Numerals ES103581004',
    referenceNumber: 'ES103581004',
    price: 59,
    category_type: 'men-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Stainless Steel',
    waterResistance: '5 Bar',
    diameterMm: 41,
    caseThicknessMm: 11,
    functions: ['Date'],
    stockQuantity: 2,
    description: "Esprit Men's Watch Classic Stainless Steel Green Numerals ES103581004",
  },
  {
    name: 'Festina Bangle Mother-of-Pearl 8948',
    referenceNumber: '8948',
    price: 122,
    category_type: 'women-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Stainless Steel',
    waterResistance: '3 Bar',
    diameterMm: 17.5,
    caseThicknessMm: 8,
    functions: ['2-Hand'],
    stockQuantity: 1,
    description: 'Festina Ladies Watch Stainless Steel Cuff/Bangle Mother-of-Pearl 8948',
  },
  {
    name: 'Fila CORTINA Chronograph FA0783-43',
    referenceNumber: 'FA0783-43',
    price: 75,
    category_type: 'men-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Stainless Steel',
    waterResistance: '10 Bar',
    diameterMm: 47,
    caseThicknessMm: 14,
    functions: ['Chronograph', 'Date'],
    stockQuantity: 1,
    description: "FILA Men's Chronograph Stainless Steel CORTINA Tachymeter Orange FA0783",
  },
  {
    name: 'Gadison Stern T-Force Automatic GS-230',
    referenceNumber: 'GS-230',
    price: 79.9,
    category_type: 'men-watches',
    movement: 'Mechanical (Automatic)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Top Leather / Bottom PU',
    waterResistance: '10 Bar',
    diameterMm: 44.5,
    caseThicknessMm: 14,
    functions: ['Date', 'No Quick Date Set'],
    stockQuantity: 1,
    description: 'Gadison Stern Automatic T-FORCE Arabic Numerals Stainless Steel Slawa 2416 GS-230',
  },
  {
    name: 'Gooix Pilot XXL Day-Date Yellow',
    referenceNumber: '5030',
    price: 49,
    category_type: 'men-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Leather',
    waterResistance: '5 Bar',
    diameterMm: 48,
    caseThicknessMm: 13.5,
    functions: ['Day-Date Display'],
    stockQuantity: 1,
    description: 'GOOIX Pilot Watch Men XXL 48mm Day-Date Yellow Numerals Stainless Steel',
  },
  {
    name: 'Jacques Cantani Venezia Diamond JC-890',
    referenceNumber: 'JC-890',
    price: 599,
    category_type: 'women-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Leather',
    waterResistance: '3 Bar',
    diameterMm: 26,
    caseThicknessMm: 7,
    functions: ['2-Hand'],
    stockQuantity: 2,
    description: 'Jacques Cantani Venezia Ladies Watch with Diamond 10 Micron Plated JC-890',
  },
  {
    name: 'Jacques Cantani Dark Horse JC-1050',
    referenceNumber: 'JC-1050',
    price: 125,
    category_type: 'men-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Stainless Steel',
    waterResistance: '10 Bar',
    diameterMm: 45,
    caseThicknessMm: 11.5,
    functions: ['Chronograph', 'Date'],
    stockQuantity: 2,
    description: "Jacques Cantani Men's Chronograph Designer Stainless Steel Black Red JC-1050",
  },
  {
    name: 'Jacques Cantani Milano Automatic ETA-2824 JC-881',
    referenceNumber: 'JC-881',
    price: 350,
    category_type: 'men-watches',
    movement: 'Mechanical (Automatic)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Leather',
    waterResistance: '10 Bar',
    diameterMm: 45,
    caseThicknessMm: 15,
    functions: ['Date'],
    stockQuantity: 1,
    description: 'Jacques Cantani Milano Automatic Swiss Made ETA-2824 JC-881',
  },
  {
    name: 'Jacques Lemans Ladies Swiss Made JL-813',
    referenceNumber: 'JL-813',
    price: 90,
    category_type: 'women-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Brass, 10 Micron Gold-plated',
    strapMaterial: 'Brass, 10 Micron Gold-plated',
    waterResistance: '3 Bar',
    diameterMm: 20,
    caseThicknessMm: 6,
    functions: ['2-Hand'],
    stockQuantity: 9,
    description: 'Jacques Lemans Ladies Watch Swiss Made 10 Micron Gold-plated Mother-of-Pearl JL-813',
  },
  {
    name: 'Jacques Lemans Quarz-Matic JL-791',
    referenceNumber: 'JL-791',
    price: 79,
    category_type: 'men-watches',
    movement: 'Kinetic (Quartz)',
    caseMaterial: 'Brass',
    strapMaterial: 'Leather',
    waterResistance: '3 Bar',
    diameterMm: 35,
    caseThicknessMm: 8.5,
    functions: ['Date'],
    stockQuantity: 4,
    description: "Jacques Lemans Quarz-Matic Men's Watch Rarity Kinetic with Energy Storage JL-791",
  },
  {
    name: 'Jaguar Friendship Swiss Made J-288/2',
    referenceNumber: 'J-288/2',
    price: 349,
    category_type: 'men-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Stainless Steel',
    waterResistance: '3 Bar',
    diameterMm: 37,
    caseThicknessMm: 9,
    functions: ['Date'],
    stockQuantity: 2,
    description: "Jaguar Men's Watch Friendship Stainless Steel Sapphire Crystal Swiss Made J-288/2",
  },
  {
    name: 'Lacher Dual Time Rectangle',
    referenceNumber: null,
    price: 69,
    category_type: 'men-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Leather',
    waterResistance: '3 Bar',
    diameterMm: 32.5,
    caseThicknessMm: 8.5,
    functions: ['2nd Time Zone'],
    stockQuantity: 5,
    description: 'Lacher Dual Time Watch Stainless Steel 2 Movements Japan Double Watch',
  },
  {
    name: 'Lancaster Chronograph Yellow 0262',
    referenceNumber: 'Ref. 0262',
    price: 85,
    category_type: 'men-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Leather',
    waterResistance: '5 Bar',
    diameterMm: 35.5,
    caseThicknessMm: 12,
    functions: ['Chronograph', 'Date', 'Screw-down Crown'],
    stockQuantity: 4,
    description: 'Lancaster Unisex Chronograph Italian Designer Watch Yellow 0262',
  },
  {
    name: "Lorus Black Children's Watch RZK-067-9",
    referenceNumber: 'RZK-067-9',
    price: 17.9,
    category_type: 'children-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Plastic',
    strapMaterial: 'Leather',
    waterResistance: '1 Bar',
    diameterMm: 26,
    caseThicknessMm: 8.5,
    functions: [],
    stockQuantity: 1,
    description: "Lorus Black Children's Watch Easy to Read Ideal for Learning School Start",
  },
  {
    name: 'M&M Ladies Stainless Steel Date 11304',
    referenceNumber: '11304',
    price: 49,
    category_type: 'women-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Stainless Steel',
    waterResistance: '3 Bar',
    diameterMm: 32,
    caseThicknessMm: 9,
    functions: ['Date'],
    stockQuantity: 1,
    description: 'M&M Ladies Watch Stainless Steel Date 11304',
  },
  {
    name: 'Mondaine Grüezi Alpine A660.30122',
    referenceNumber: 'A660.30122.xxEM',
    price: 59,
    category_type: 'women-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Brass',
    strapMaterial: 'Leather',
    waterResistance: '3 Bar',
    diameterMm: 37,
    caseThicknessMm: 9,
    functions: [],
    stockQuantity: 5,
    description: 'Mondaine Ladies Watch Traditional Alpine Grüezi Silver/Red',
  },
  {
    name: 'Morgan & Headley Quadriga Swiss Made MH-990',
    referenceNumber: 'MH-990',
    price: 399,
    category_type: 'men-watches',
    movement: 'Mechanical (Automatic)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Leather',
    waterResistance: '3 Bar',
    diameterMm: 38.5,
    caseThicknessMm: 12,
    functions: ['Date', 'Screw-down Crown'],
    stockQuantity: 1,
    description: 'Morgan & Headley Automatic Swiss Made ETA 2824-2 MH-990',
  },
  {
    name: 'Morgan & Headley Dual Time MH-520',
    referenceNumber: 'MH-520',
    price: 99,
    category_type: 'men-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Stainless Steel',
    waterResistance: '10 Bar',
    diameterMm: 42.5,
    caseThicknessMm: 12,
    functions: ['2nd Time Zone', 'Rotating Bezel', 'Date'],
    stockQuantity: 3,
    description: "Morgan & Headley Dual Time Men's Watch Stainless Steel Black MH-520",
  },
  {
    name: 'OBAKU Ladies Milanese Gold V130LGGMG',
    referenceNumber: 'V130LGGMG',
    price: 89,
    category_type: 'women-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Stainless Steel',
    waterResistance: '3 Bar',
    diameterMm: 24,
    caseThicknessMm: 7,
    functions: [],
    stockQuantity: 7,
    description: 'OBAKU Ladies Watch Stainless Steel Gold-plated Milanese Bracelet V130LGGMG',
  },
  {
    name: 'Pierre Cardin Chronograph Rose Gold PC106032F10',
    referenceNumber: 'PC106032F10',
    price: 149,
    category_type: 'men-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Stainless Steel',
    waterResistance: '5 Bar',
    diameterMm: 36.5,
    caseThicknessMm: 12.5,
    functions: ['Chronograph', 'Date'],
    stockQuantity: 2,
    description: "Pierre Cardin Men's Chronograph Stainless Steel with Rose Gold PC106032F10",
  },
  {
    name: 'Quality Time Ladies Milanese QLS-30405-11M',
    referenceNumber: 'QLS-30405-11M',
    price: 49,
    category_type: 'women-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Stainless Steel',
    waterResistance: '3 Bar',
    diameterMm: 33,
    caseThicknessMm: 7.5,
    functions: [],
    stockQuantity: 8,
    description: 'Quality Time Ladies Watch 3 Bar Stainless Steel Milanese Bracelet 30mm QLS-30405-11M',
  },
  {
    name: 'Q&Q Analog-Digital World Time MDV2-302',
    referenceNumber: 'MDV2-302',
    price: 29,
    category_type: 'men-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Plastic',
    strapMaterial: 'Silicone',
    waterResistance: '5 Bar',
    diameterMm: 43,
    caseThicknessMm: 15,
    functions: ['Digital World Time', '5 Alarms', 'Timer', 'Stopwatch', '30 Memory', 'Light'],
    stockQuantity: 2,
    description: "Q&Q Men's Analog-Digital World Time 5 Alarms 30-Memory Light Stopwatch MDV2-302",
  },
  {
    name: 'Osco Ladies Expansion Band Zirconia SDC',
    referenceNumber: 'SDC',
    price: 24.9,
    category_type: 'women-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Brass',
    strapMaterial: 'Stainless Steel',
    waterResistance: '3 Bar',
    diameterMm: 32,
    caseThicknessMm: 10,
    functions: [],
    stockQuantity: 6,
    description: 'Osco Ladies Watch Expansion Band Zirconia 32mm SDC',
  },
  {
    name: 'Revue Thommen Streamline Copper 6510005',
    referenceNumber: '6510005',
    price: 199,
    category_type: 'men-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Stainless Steel',
    waterResistance: '15 Bar',
    diameterMm: 38,
    caseThicknessMm: 8.5,
    functions: ['Date', 'Screw-down Crown', 'Limited Edition'],
    stockQuantity: 1,
    description: 'Revue Thommen STREAM LINE 38mm Copper Dial Swiss Made 6510005',
  },
  {
    name: 'Richter & Söhne Ceramic 8 Diamonds 1032044',
    referenceNumber: '1032044',
    price: 139,
    category_type: 'women-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Stainless Steel with Ceramic Elements',
    waterResistance: '3 Bar',
    diameterMm: 32.5,
    caseThicknessMm: 8,
    functions: [],
    stockQuantity: 1,
    description: 'Richter & Söhne Ladies Watch Stainless Steel Ceramic 8 Diamonds Gold-plated 1032044',
  },
  {
    name: 'Rivado Men Anthracite Milanese RIGS-30341-52M',
    referenceNumber: 'RIGS-30341-52M',
    price: 49,
    category_type: 'men-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Stainless Steel',
    waterResistance: '5 Bar',
    diameterMm: 41,
    caseThicknessMm: 8,
    functions: ['Date'],
    stockQuantity: 1,
    description: "Rivado Men's Watch Stainless Steel Anthracite Milanese Date 41mm RIGS-30341-52M",
  },
  {
    name: 'Roamer Dreamline Ladies Blue 619.953',
    referenceNumber: '619953',
    price: 119,
    category_type: 'women-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Stainless Steel',
    waterResistance: '3 Bar',
    diameterMm: 20.5,
    caseThicknessMm: 6,
    functions: ['2-Hand'],
    stockQuantity: 1,
    description: 'Roamer Ladies Watch Dreamline 1 Swiss Made Stainless Steel Blue 619.953',
  },
  {
    name: 'Xemex X-TIDE Automatic Swiss Made 22400.02',
    referenceNumber: '22400.02',
    price: 599,
    category_type: 'men-watches',
    movement: 'Mechanical (Automatic)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Rubber',
    waterResistance: '5 Bar',
    diameterMm: 47,
    caseThicknessMm: 13,
    functions: ['Date'],
    stockQuantity: 5,
    description: "Xemex X-TIDE Automatic Swiss Made 22400.02 Men's Watch",
  },
  {
    name: 'Manguun Ladies Milanese MULA-91317-60M',
    referenceNumber: 'MULA-91317-60M',
    price: 25,
    category_type: 'women-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Brass',
    strapMaterial: 'Stainless Steel',
    waterResistance: '3 Bar',
    diameterMm: 38,
    caseThicknessMm: 8,
    functions: [],
    stockQuantity: 5,
    description: 'Manguun Ladies Watch Milanese Bracelet MULA-91317-60M',
  },
  {
    name: 'Quality Time GPS World Time 80125',
    referenceNumber: '80125',
    price: 119,
    category_type: 'men-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Stainless Steel',
    waterResistance: '10 Bar',
    diameterMm: 46,
    caseThicknessMm: 14,
    functions: ['Digital World Time', 'Geo-Position', 'Light', 'Stopwatch'],
    stockQuantity: 1,
    description: 'Quality Time GPS World Time Chronograph Stainless Steel 80125',
  },
  {
    name: 'Master Time Radio-Controlled Ladies MTLS-10325',
    referenceNumber: 'MTLS-10325',
    price: 49,
    category_type: 'women-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Leather',
    waterResistance: '1 Bar',
    diameterMm: 32,
    caseThicknessMm: 11,
    functions: [],
    stockQuantity: 2,
    description: 'Master Time Radio-Controlled Ladies Watch Easy to Read Brown Strap MTLS-10325',
  },
  {
    name: 'ETT Solar WOOD EGW-12127-32',
    referenceNumber: 'GW-12127-32',
    price: 59,
    category_type: 'men-watches',
    movement: 'Battery (Solar)',
    caseMaterial: 'Stainless Steel + Wood',
    strapMaterial: 'Wood',
    waterResistance: '3 Bar',
    diameterMm: 42,
    caseThicknessMm: 12,
    functions: ['Date'],
    stockQuantity: 3,
    description: 'ETT EcoTechTime Solar Men\'s Watch OSOYOOS WOOD Blue EGW-12127-32',
  },
  {
    name: 'ETT Eco Tech Time Radio-Solar ELS-11269-21M',
    referenceNumber: 'ELS-11269-21M',
    price: 79,
    category_type: 'women-watches',
    movement: 'Battery (Solar)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Stainless Steel',
    waterResistance: '3 Bar',
    diameterMm: 34,
    caseThicknessMm: 11.5,
    functions: [],
    stockQuantity: 3,
    description: 'ETT Eco Tech Time Radio-Solar 10 Bar Stainless Steel ELS-11269-21M',
  },
  {
    name: 'Cerruti 1881 Automatic Power Reserve CRA074C2731',
    referenceNumber: 'CRA074C2731',
    price: 229,
    category_type: 'men-watches',
    movement: 'Mechanical (Automatic)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Leather',
    waterResistance: '1 Bar',
    diameterMm: 44,
    caseThicknessMm: 15,
    functions: ['Date', 'Power Reserve', 'Off-center Small Seconds', 'No Quick Date Set'],
    stockQuantity: 1,
    description: "Cerruti 1881 Automatic Men's Watch Power Reserve Date Rose Gold CRA074C2731",
  },
  {
    name: 'Sinar Digital Yellow LED UE-30-5',
    referenceNumber: 'UE-30-5',
    price: 24.9,
    category_type: 'men-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Plastic',
    strapMaterial: 'Plastic',
    waterResistance: '1 Bar',
    diameterMm: 45,
    caseThicknessMm: 14,
    functions: ['Date'],
    stockQuantity: 3,
    description: 'Sinar Digital Unisex Resin Strap 12/24 Hours Yellow LED UE-30-5',
  },
  {
    name: 'Bruno Banani ZENO Black BR20994',
    referenceNumber: 'BR20994',
    price: 49,
    category_type: 'men-watches',
    movement: 'Battery (Quartz)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Top Leather / Bottom Textile',
    waterResistance: '3 Bar',
    diameterMm: 42,
    caseThicknessMm: 8,
    functions: ['2-Hand'],
    stockQuantity: 1,
    description: "Bruno Banani ZENO Stainless Steel Black Designer Men's Watch BR20994",
  },
  {
    name: 'Swiss Military Hanowa Patrol Bicolor 05-5198.55',
    referenceNumber: '05-5198.55',
    price: 298,
    category_type: 'men-watches',
    movement: 'Mechanical (Automatic)',
    caseMaterial: 'Stainless Steel',
    strapMaterial: 'Stainless Steel',
    waterResistance: '10 Bar',
    diameterMm: 39,
    caseThicknessMm: 11,
    functions: ['Date'],
    stockQuantity: 3,
    description: 'Swiss Military Hanowa Patrol Swiss Automatic Bicolor Swiss Made 05-5198.55',
  },
];

async function main(): Promise<void> {
  console.log('Kampfer seed — ensuring categories...');

  // Upsert all required categories and build a slug→id map
  const categoryMap: Record<string, string> = {};
  for (const cat of CATEGORIES) {
    const record = await prisma.category.upsert({
      where: { slug: cat.slug },
      update: {},
      create: { name: cat.name, slug: cat.slug },
    });
    categoryMap[cat.slug] = record.id;
    console.log(`  Category ready: ${cat.slug} (${record.id})`);
  }

  console.log(`\nSeeding ${products.length} products...\n`);

  let seeded = 0;
  let skipped = 0;
  let failed = 0;

  for (const p of products) {
    try {
      // Duplicate check: by referenceNumber if present, otherwise by name
      const existing = await prisma.product.findFirst({
        where: p.referenceNumber
          ? { referenceNumber: p.referenceNumber }
          : { name: p.name },
        select: { id: true },
      });

      if (existing) {
        console.log(`  SKIP  ${p.name} (${p.referenceNumber ?? 'no ref'})`);
        skipped++;
        continue;
      }

      const categoryId = categoryMap[p.category_type];
      if (!categoryId) {
        throw new Error(`Unknown category_type: "${p.category_type}"`);
      }

      await prisma.product.create({
        data: {
          name: p.name,
          description: p.description,
          price: p.price,
          stockQuantity: p.stockQuantity,
          isActive: true,
          referenceNumber: p.referenceNumber ?? undefined,
          movement: p.movement,
          caseMaterial: p.caseMaterial,
          strapMaterial: p.strapMaterial,
          waterResistance: p.waterResistance,
          functions: p.functions,
          category_type: p.category_type,
          currency: 'EUR',
          diameterMm: p.diameterMm,
          caseThicknessMm: p.caseThicknessMm,
          categoryId,
        },
      });

      console.log(`  OK    ${p.name}`);
      seeded++;
    } catch (err) {
      console.error(`  FAIL  ${p.name} — ${(err as Error).message}`);
      failed++;
    }
  }

  console.log(`\n----------------------------------------`);
  console.log(`${seeded} products seeded, ${skipped} skipped, ${failed} failed`);
  console.log('----------------------------------------');
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
